/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChatResponse,
  StringResponse,
} from '../models/index';
import {
    ChatResponseFromJSON,
    ChatResponseToJSON,
    StringResponseFromJSON,
    StringResponseToJSON,
} from '../models/index';

export interface CreateChatRequest {
    senderId: string;
    receiverId: string;
}

/**
 * ChatApi - interface
 * 
 * @export
 * @interface ChatApiInterface
 */
export interface ChatApiInterface {
    /**
     * 
     * @param {string} senderId 
     * @param {string} receiverId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    createChatRaw(requestParameters: CreateChatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringResponse>>;

    /**
     */
    createChat(requestParameters: CreateChatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringResponse>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    getChatsByReceiverRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ChatResponse>>>;

    /**
     */
    getChatsByReceiver(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ChatResponse>>;

}

/**
 * 
 */
export class ChatApi extends runtime.BaseAPI implements ChatApiInterface {

    /**
     */
    async createChatRaw(requestParameters: CreateChatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringResponse>> {
        if (requestParameters['senderId'] == null) {
            throw new runtime.RequiredError(
                'senderId',
                'Required parameter "senderId" was null or undefined when calling createChat().'
            );
        }

        if (requestParameters['receiverId'] == null) {
            throw new runtime.RequiredError(
                'receiverId',
                'Required parameter "receiverId" was null or undefined when calling createChat().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['senderId'] != null) {
            queryParameters['senderId'] = requestParameters['senderId'];
        }

        if (requestParameters['receiverId'] != null) {
            queryParameters['receiverId'] = requestParameters['receiverId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/chats`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StringResponseFromJSON(jsonValue));
    }

    /**
     */
    async createChat(requestParameters: CreateChatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringResponse> {
        const response = await this.createChatRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getChatsByReceiverRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ChatResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/chats`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ChatResponseFromJSON));
    }

    /**
     */
    async getChatsByReceiver(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ChatResponse>> {
        const response = await this.getChatsByReceiverRaw(initOverrides);
        return await response.value();
    }

}
