/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
    MessageToJSONTyped,
} from './Message';

/**
 * 
 * @export
 * @interface Chat
 */
export interface Chat {
    /**
     * 
     * @type {Date}
     * @memberof Chat
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Chat
     */
    lastModifiedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Chat
     */
    id?: string;
    /**
     * 
     * @type {User}
     * @memberof Chat
     */
    sender?: User;
    /**
     * 
     * @type {User}
     * @memberof Chat
     */
    receiver?: User;
    /**
     * 
     * @type {Array<Message>}
     * @memberof Chat
     */
    messages?: Array<Message>;
    /**
     * 
     * @type {string}
     * @memberof Chat
     */
    lastMessage?: string;
    /**
     * 
     * @type {Date}
     * @memberof Chat
     */
    lastMessageTime?: Date;
}

/**
 * Check if a given object implements the Chat interface.
 */
export function instanceOfChat(value: object): value is Chat {
    return true;
}

export function ChatFromJSON(json: any): Chat {
    return ChatFromJSONTyped(json, false);
}

export function ChatFromJSONTyped(json: any, ignoreDiscriminator: boolean): Chat {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'lastModifiedAt': json['lastModifiedAt'] == null ? undefined : (new Date(json['lastModifiedAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'sender': json['sender'] == null ? undefined : UserFromJSON(json['sender']),
        'receiver': json['receiver'] == null ? undefined : UserFromJSON(json['receiver']),
        'messages': json['messages'] == null ? undefined : ((json['messages'] as Array<any>).map(MessageFromJSON)),
        'lastMessage': json['lastMessage'] == null ? undefined : json['lastMessage'],
        'lastMessageTime': json['lastMessageTime'] == null ? undefined : (new Date(json['lastMessageTime'])),
    };
}

export function ChatToJSON(json: any): Chat {
    return ChatToJSONTyped(json, false);
}

export function ChatToJSONTyped(value?: Chat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'lastModifiedAt': value['lastModifiedAt'] == null ? undefined : ((value['lastModifiedAt']).toISOString()),
        'id': value['id'],
        'sender': UserToJSON(value['sender']),
        'receiver': UserToJSON(value['receiver']),
        'messages': value['messages'] == null ? undefined : ((value['messages'] as Array<any>).map(MessageToJSON)),
        'lastMessage': value['lastMessage'],
        'lastMessageTime': value['lastMessageTime'] == null ? undefined : ((value['lastMessageTime']).toISOString()),
    };
}

