/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageRequest
 */
export interface MessageRequest {
    /**
     * 
     * @type {number}
     * @memberof MessageRequest
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof MessageRequest
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof MessageRequest
     */
    sortBy?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageRequest
     */
    sortDir?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageRequest
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageRequest
     */
    senderId?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageRequest
     */
    receiverId?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageRequest
     */
    chatId?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageRequest
     */
    type?: MessageRequestTypeEnum;
}


/**
 * @export
 */
export const MessageRequestTypeEnum = {
    Text: 'TEXT',
    Image: 'IMAGE',
    Video: 'VIDEO',
    Audio: 'AUDIO',
    Document: 'DOCUMENT'
} as const;
export type MessageRequestTypeEnum = typeof MessageRequestTypeEnum[keyof typeof MessageRequestTypeEnum];


/**
 * Check if a given object implements the MessageRequest interface.
 */
export function instanceOfMessageRequest(value: object): value is MessageRequest {
    return true;
}

export function MessageRequestFromJSON(json: any): MessageRequest {
    return MessageRequestFromJSONTyped(json, false);
}

export function MessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'sortBy': json['sortBy'] == null ? undefined : json['sortBy'],
        'sortDir': json['sortDir'] == null ? undefined : json['sortDir'],
        'content': json['content'] == null ? undefined : json['content'],
        'senderId': json['senderId'] == null ? undefined : json['senderId'],
        'receiverId': json['receiverId'] == null ? undefined : json['receiverId'],
        'chatId': json['chatId'] == null ? undefined : json['chatId'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function MessageRequestToJSON(json: any): MessageRequest {
    return MessageRequestToJSONTyped(json, false);
}

export function MessageRequestToJSONTyped(value?: MessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'size': value['size'],
        'sortBy': value['sortBy'],
        'sortDir': value['sortDir'],
        'content': value['content'],
        'senderId': value['senderId'],
        'receiverId': value['receiverId'],
        'chatId': value['chatId'],
        'type': value['type'],
    };
}

