/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Chat } from './Chat';
import {
    ChatFromJSON,
    ChatFromJSONTyped,
    ChatToJSON,
    ChatToJSONTyped,
} from './Chat';

/**
 * 
 * @export
 * @interface Message
 */
export interface Message {
    /**
     * 
     * @type {Date}
     * @memberof Message
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Message
     */
    lastModifiedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    state?: MessageStateEnum;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    type?: MessageTypeEnum;
    /**
     * 
     * @type {Chat}
     * @memberof Message
     */
    chat?: Chat;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    senderId?: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    receiverId?: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    mediaFilePath?: string;
}


/**
 * @export
 */
export const MessageStateEnum = {
    Sent: 'SENT',
    Seen: 'SEEN'
} as const;
export type MessageStateEnum = typeof MessageStateEnum[keyof typeof MessageStateEnum];

/**
 * @export
 */
export const MessageTypeEnum = {
    Text: 'TEXT',
    Image: 'IMAGE',
    Video: 'VIDEO',
    Audio: 'AUDIO',
    Document: 'DOCUMENT'
} as const;
export type MessageTypeEnum = typeof MessageTypeEnum[keyof typeof MessageTypeEnum];


/**
 * Check if a given object implements the Message interface.
 */
export function instanceOfMessage(value: object): value is Message {
    return true;
}

export function MessageFromJSON(json: any): Message {
    return MessageFromJSONTyped(json, false);
}

export function MessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Message {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'lastModifiedAt': json['lastModifiedAt'] == null ? undefined : (new Date(json['lastModifiedAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'content': json['content'] == null ? undefined : json['content'],
        'state': json['state'] == null ? undefined : json['state'],
        'type': json['type'] == null ? undefined : json['type'],
        'chat': json['chat'] == null ? undefined : ChatFromJSON(json['chat']),
        'senderId': json['senderId'] == null ? undefined : json['senderId'],
        'receiverId': json['receiverId'] == null ? undefined : json['receiverId'],
        'mediaFilePath': json['mediaFilePath'] == null ? undefined : json['mediaFilePath'],
    };
}

export function MessageToJSON(json: any): Message {
    return MessageToJSONTyped(json, false);
}

export function MessageToJSONTyped(value?: Message | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'lastModifiedAt': value['lastModifiedAt'] == null ? undefined : ((value['lastModifiedAt']).toISOString()),
        'id': value['id'],
        'content': value['content'],
        'state': value['state'],
        'type': value['type'],
        'chat': ChatToJSON(value['chat']),
        'senderId': value['senderId'],
        'receiverId': value['receiverId'],
        'mediaFilePath': value['mediaFilePath'],
    };
}

