/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
    PageableObjectToJSONTyped,
} from './PageableObject';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
    MessageToJSONTyped,
} from './Message';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
    SortObjectToJSONTyped,
} from './SortObject';

/**
 * 
 * @export
 * @interface PageMessage
 */
export interface PageMessage {
    /**
     * 
     * @type {number}
     * @memberof PageMessage
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMessage
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMessage
     */
    size?: number;
    /**
     * 
     * @type {Array<Message>}
     * @memberof PageMessage
     */
    content?: Array<Message>;
    /**
     * 
     * @type {number}
     * @memberof PageMessage
     */
    number?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageMessage
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageMessage
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageMessage
     */
    numberOfElements?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageMessage
     */
    sort?: SortObject;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageMessage
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageMessage
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageMessage interface.
 */
export function instanceOfPageMessage(value: object): value is PageMessage {
    return true;
}

export function PageMessageFromJSON(json: any): PageMessage {
    return PageMessageFromJSONTyped(json, false);
}

export function PageMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(MessageFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'sort': json['sort'] == null ? undefined : SortObjectFromJSON(json['sort']),
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageMessageToJSON(json: any): PageMessage {
    return PageMessageToJSONTyped(json, false);
}

export function PageMessageToJSONTyped(value?: PageMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(MessageToJSON)),
        'number': value['number'],
        'first': value['first'],
        'last': value['last'],
        'numberOfElements': value['numberOfElements'],
        'sort': SortObjectToJSON(value['sort']),
        'pageable': PageableObjectToJSON(value['pageable']),
        'empty': value['empty'],
    };
}

