/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Chat } from './Chat';
import {
    ChatFromJSON,
    ChatFromJSONTyped,
    ChatToJSON,
    ChatToJSONTyped,
} from './Chat';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    lastModifiedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: string;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    lastSeen?: Date;
    /**
     * 
     * @type {Array<Chat>}
     * @memberof User
     */
    chatsAsSender?: Array<Chat>;
    /**
     * 
     * @type {Array<Chat>}
     * @memberof User
     */
    chatsAsReceiver?: Array<Chat>;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    userOnline?: boolean;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'lastModifiedAt': json['lastModifiedAt'] == null ? undefined : (new Date(json['lastModifiedAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'email': json['email'] == null ? undefined : json['email'],
        'lastSeen': json['lastSeen'] == null ? undefined : (new Date(json['lastSeen'])),
        'chatsAsSender': json['chatsAsSender'] == null ? undefined : ((json['chatsAsSender'] as Array<any>).map(ChatFromJSON)),
        'chatsAsReceiver': json['chatsAsReceiver'] == null ? undefined : ((json['chatsAsReceiver'] as Array<any>).map(ChatFromJSON)),
        'userOnline': json['userOnline'] == null ? undefined : json['userOnline'],
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'lastModifiedAt': value['lastModifiedAt'] == null ? undefined : ((value['lastModifiedAt']).toISOString()),
        'id': value['id'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
        'lastSeen': value['lastSeen'] == null ? undefined : ((value['lastSeen']).toISOString()),
        'chatsAsSender': value['chatsAsSender'] == null ? undefined : ((value['chatsAsSender'] as Array<any>).map(ChatToJSON)),
        'chatsAsReceiver': value['chatsAsReceiver'] == null ? undefined : ((value['chatsAsReceiver'] as Array<any>).map(ChatToJSON)),
        'userOnline': value['userOnline'],
    };
}

